NUTS_CODES_DICT = {
    'CZ': 'Česká republika',
    'CZ0': 'Česká republika',
    'CZZ': 'Extra-Regio',
    'CZZZZ': 'Extra-Regio',
    'CZZZ': 'Extra-Regio',
    'CZ010': 'Hlavní město Praha',
    'CZ031': 'Jihočeský kraj',
    'CZ064': 'Jihomoravský kraj',
    'CZ06': 'Jihovýchod',
    'CZ03': 'Jihozápad',
    'CZ041': 'Karlovarský kraj',
    'CZ052': 'Královéhradecký kraj',
    'CZ051': 'Liberecký kraj',
    'CZ08': 'Moravskoslezsko',
    'CZ080': 'Moravskoslezský kraj',
    'CZ071': 'Olomoucký kraj',
    'CZ053': 'Pardubický kraj',
    'CZ032': 'Plzeňský kraj',
    'CZ01': 'Praha',
    'CZ05': 'Severovýchod',
    'CZ04': 'Severozápad',
    'CZ02': 'Střední Čechy',
    'CZ07': 'Střední Morava',
    'CZ020': 'Středočeský kraj',
    'CZ042': 'Ústecký kraj',
    'CZ063': 'Vysočina',
    'CZ072': 'Zlínský kraj'
}

LAU_CODES_DICT = {
    'CZ0201': 'Benešov',
    'CZ0202': 'Beroun',
    'CZ0641': 'Blansko',
    'CZ0642': 'Brno-město',
    'CZ0643': 'Brno-venkov',
    'CZ0801': 'Bruntál',
    'CZ0644': 'Břeclav',
    'CZ0411': 'Cheb',
    'CZ0422': 'Chomutov',
    'CZ0531': 'Chrudim',
    'CZ0321': 'Domažlice',
    'CZ0421': 'Děčín',
    'CZ0802': 'Frýdek-Místek',
    'CZ0631': 'Havlíčkův Brod',
    'CZ0100': 'Hlavní město Praha',
    'CZ0645': 'Hodonín',
    'CZ0521': 'Hradec Králové',
    'CZ0512': 'Jablonec nad Nisou',
    'CZ0711': 'Jeseník',
    'CZ0632': 'Jihlava',
    'CZ0313': 'Jindřichův Hradec',
    'CZ0522': 'Jičín',
    'CZ0412': 'Karlovy Vary',
    'CZ0803': 'Karviná',
    'CZ0203': 'Kladno',
    'CZ0322': 'Klatovy',
    'CZ0204': 'Kolín',
    'CZ0721': 'Kroměříž',
    'CZ0205': 'Kutná Hora',
    'CZ0513': 'Liberec',
    'CZ0423': 'Litoměřice',
    'CZ0424': 'Louny',
    'CZ0207': 'Mladá Boleslav',
    'CZ0425': 'Most',
    'CZ0206': 'Mělník',
    'CZ0804': 'Nový Jičín',
    'CZ0208': 'Nymburk',
    'CZ0523': 'Náchod',
    'CZ0712': 'Olomouc',
    'CZ0805': 'Opava',
    'CZ0806': 'Ostrava-město',
    'CZ0532': 'Pardubice',
    'CZ0633': 'Pelhřimov',
    'CZ0324': 'Plzeň-jih',
    'CZ0323': 'Plzeň-město',
    'CZ0325': 'Plzeň-sever',
    'CZ0315': 'Prachatice',
    'CZ0209': 'Praha-východ',
    'CZ020A': 'Praha-západ',
    'CZ0713': 'Prostějov',
    'CZ0314': 'Písek',
    'CZ0714': 'Přerov',
    'CZ020B': 'Příbram',
    'CZ020C': 'Rakovník',
    'CZ0326': 'Rokycany',
    'CZ0524': 'Rychnov nad Kněžnou',
    'CZ0514': 'Semily',
    'CZ0413': 'Sokolov',
    'CZ0316': 'Strakonice',
    'CZ0533': 'Svitavy',
    'CZ0327': 'Tachov',
    'CZ0426': 'Teplice',
    'CZ0525': 'Trutnov',
    'CZ0317': 'Tábor',
    'CZ0634': 'Třebíč',
    'CZ0722': 'Uherské Hradiště',
    'CZ0723': 'Vsetín',
    'CZ0646': 'Vyškov',
    'CZ0724': 'Zlín',
    'CZ0647': 'Znojmo',
    'CZ0715': 'Šumperk',
    'CZ0635': 'Žďár nad Sázavou',
    'CZ0511': 'Česká Lípa',
    'CZ0311': 'České Budějovice',
    'CZ0312': 'Český Krumlov',
    'CZ0427': 'Ústí nad Labem',
    'CZ0534': 'Ústí nad Orlicí'
}

COUNTRY_CODES_DICT = {
    'AF': 'Afghánská islámská republika',
    'AX': 'Provincie Alandy',
    'AL': 'Albánská republika',
    'DZ': 'Alžírská demokratická a lidová republika',
    'AS': 'Území Americká Samoa',
    'VI': 'Americké Panenské ostrovy',
    'AD': 'Andorrské knížectví',
    'AO': 'Angolská republika',
    'AI': 'Anguilla',
    'AQ': 'Antarktida',
    'AG': 'Antigua a Barbuda',
    'AR': 'Argentinská republika',
    'AM': 'Arménská republika',
    'AW': 'Aruba',
    'AU': 'Australské společenství',
    'AZ': 'Ázerbájdžánská republika',
    'BS': 'Bahamské společenství',
    'BH': 'Království Bahrajn',
    'BD': 'Bangladéšská lidová republika',
    'BB': 'Barbados',
    'BE': 'Belgické království',
    'BZ': 'Belize',
    'BY': 'Běloruská republika',
    'BJ': 'Beninská republika',
    'BM': 'Bermudy',
    'BT': 'Bhútánské království',
    'BO': 'Mnohonárodní stát Bolívie',
    'BQ': 'Bonaire, Svatý Eustach a Saba',
    'BA': 'Bosna a Hercegovina',
    'BW': 'Botswanská republika',
    'BV': 'Bouvetův ostrov',
    'BR': 'Brazilská federativní republika',
    'IO': 'Britské území v Indickém oceánu',
    'VG': 'Britské Panenské ostrovy',
    'BN': 'Stát Brunej Darussalam',
    'BG': 'Bulharská republika',
    'BF': 'Burkina Faso',
    'BI': 'Burundská republika',
    'CK': 'Cookovy ostrovy',
    'CW': 'Země Curaçao',
    'TD': 'Čadská republika',
    'ME': 'Černá Hora',
    'CZ': 'Česká republika',
    'CN': 'Čínská lidová republika',
    'DK': 'Dánské království',
    'CD': 'Konžská demokratická republika',
    'DM': 'Dominické společenství',
    'DO': 'Dominikánská republika',
    'DJ': 'Džibutská republika',
    'EG': 'Egyptská arabská republika',
    'EC': 'Ekvádorská republika',
    'ER': 'Stát Eritrea',
    'EE': 'Estonská republika',
    'ET': 'Etiopská federativní demokratická republika',
    'FO': 'Faerské ostrovy',
    'FK': 'Falklandy (Malvíny)',
    'FJ': 'Fidžijská republika',
    'PH': 'Filipínská republika',
    'FI': 'Finská republika',
    'FR': 'Francouzská republika',
    'GF': 'Francouzská Guyana',
    'TF': 'Francouzská jižní a antarktická území',
    'PF': 'Francouzská Polynésie',
    'GA': 'Gabonská republika',
    'GM': 'Gambijská republika',
    'GH': 'Ghanská republika',
    'GI': 'Gibraltar',
    'GD': 'Grenada',
    'GL': 'Grónsko',
    'GE': 'Gruzie',
    'GP': 'Region Guadeloupe',
    'GU': 'Teritorium Guam',
    'GT': 'Guatemalská republika',
    'GG': 'Bailiwick Guernsey',
    'GN': 'Guinejská republika',
    'GW': 'Republika Guinea-Bissau',
    'GY': 'Guyanská kooperativní republika',
    'HT': 'Republika Haiti',
    'HM': 'Heardův ostrov a MacDonaldovy ostrovy',
    'HN': 'Honduraská republika',
    'HK': 'Zvláštní administrativní oblast Čínské lidové republiky Hongkong',
    'CL': 'Chilská republika',
    'HR': 'Chorvatská republika',
    'IN': 'Indická republika',
    'ID': 'Indonéská republika',
    'IQ': 'Irácká republika',
    'IR': 'Íránská islámská republika',
    'IE': 'Irsko',
    'IS': 'Islandská republika',
    'IT': 'Italská republika',
    'IL': 'Stát Izrael',
    'JM': 'Jamajka',
    'JP': 'Japonsko',
    'YE': 'Jemenská republika',
    'JE': 'Bailiwick Jersey',
    'ZA': 'Jihoafrická republika',
    'GS': 'Jižní Georgie a Jižní Sandwichovy ostrovy',
    'SS': 'Jihosúdánská republika',
    'JO': 'Jordánské hášimovské království',
    'KY': 'Kajmanské ostrovy',
    'KH': 'Kambodžské království',
    'CM': 'Kamerunská republika',
    'CA': 'Kanada',
    'CV': 'Kapverdská republika',
    'QA': 'Stát Katar',
    'KZ': 'Republika Kazachstán',
    'KE': 'Keňská republika',
    'KI': 'Republika Kiribati',
    'CC': 'Území Kokosové (Keelingovy) ostrovy',
    'CO': 'Kolumbijská republika',
    'KM': 'Komorský svaz',
    'CG': 'Konžská republika',
    'KP': 'Korejská lidově demokratická republika',
    'KR': 'Korejská republika',
    'XK': 'Kosovská republika',
    'CR': 'Kostarická republika',
    'CU': 'Kubánská republika',
    'KW': 'Kuvajtský stát',
    'CY': 'Kyperská republika',
    'KG': 'Kyrgyzská republika',
    'LA': 'Laoská lidově demokratická republika',
    'LS': 'Lesothské království',
    'LB': 'Libanonská republika',
    'LR': 'Liberijská republika',
    'LY': 'Libyjský stát',
    'LI': 'Lichtenštejnské knížectví',
    'LT': 'Litevská republika',
    'LV': 'Lotyšská republika',
    'LU': 'Lucemburské velkovévodství',
    'MO': 'Zvláštní administrativní oblast Čínské lidové republiky Macao',
    'MG': 'Madagaskarská republika',
    'HU': 'Maďarsko',
    'MK': 'Republika Severní Makedonie',
    'MY': 'Malajsie',
    'MW': 'Malawiská republika',
    'MV': 'Maledivská republika',
    'ML': 'Republika Mali',
    'MT': 'Maltská republika',
    'IM': 'Ostrov Man',
    'MA': 'Marocké království',
    'MH': 'Republika Marshallovy ostrovy',
    'MQ': 'Martinik',
    'MU': 'Mauricijská republika',
    'MR': 'Mauritánská islámská republika',
    'YT': 'Departement Mayotte',
    'UM': 'Menší odlehlé ostrovy USA',
    'MX': 'Spojené státy mexické',
    'FM': 'Federativní státy Mikronésie',
    'MD': 'Moldavská republika',
    'MC': 'Monacké knížectví',
    'MN': 'Mongolsko',
    'MS': 'Montserrat',
    'MZ': 'Mosambická republika',
    'MM': 'Republika Myanmarský svaz',
    'NA': 'Namibijská republika',
    'NR': 'Republika Nauru',
    'DE': 'Spolková republika Německo',
    'NP': 'Nepálská federativní demokratická republika',
    'NE': 'Nigerská republika',
    'NG': 'Nigerijská federativní republika',
    'NI': 'Nikaragujská republika',
    'NU': 'Niue',
    'NL': 'Nizozemsko',
    'NF': 'Území Norfolk',
    'NO': 'Norské království',
    'NC': 'Nová Kaledonie',
    'NZ': 'Nový Zéland',
    'OM': 'Sultanát Omán',
    'PK': 'Pákistánská islámská republika',
    'PW': 'Republika Palau',
    'PS': 'Palestinská autonomní území',
    'PA': 'Panamská republika',
    'PG': 'Nezávislý stát Papua Nová Guinea',
    'PY': 'Paraguayská republika',
    'PE': 'Peruánská republika',
    'PN': 'Pitcairnovy ostrovy',
    'CI': 'Republika Pobřeží slonoviny',
    'PL': 'Polská republika',
    'PR': 'Portorické společenství',
    'PT': 'Portugalská republika',
    'AT': 'Rakouská republika',
    'RE': 'Region Réunion',
    'GQ': 'Republika Rovníková Guinea',
    'RO': 'Rumunsko',
    'RU': 'Ruská federace',
    'RW': 'Rwandská republika',
    'GR': 'Řecká republika',
    'PM': 'Územní společenství Saint Pierre a Miquelon',
    'SV': 'Salvadorská republika',
    'WS': 'Nezávislý stát Samoa',
    'SM': 'Republika San Marino',
    'SA': 'Království Saúdská Arábie',
    'SN': 'Senegalská republika',
    'MP': 'Společenství Severní Mariany',
    'SC': 'Seychelská republika',
    'SL': 'Republika Sierra Leone',
    'SG': 'Singapurská republika',
    'SK': 'Slovenská republika',
    'SI': 'Slovinská republika',
    'SO': 'Somálská federativní republika',
    'AE': 'Stát Spojené arabské emiráty',
    'US': 'Spojené státy americké',
    'RS': 'Srbská republika',
    'CF': 'Středoafrická republika',
    'SD': 'Súdánská republika',
    'SR': 'Surinamská republika',
    'SH': 'Svatá Helena, Ascension a Tristan da Cunha',
    'LC': 'Svatá Lucie',
    'BL': 'Společenství Svatý Bartoloměj',
    'KN': 'Federace Svatý Kryštof a Nevis',
    'MF': 'Společenství Svatý Martin',
    'SX': 'Svatý Martin (NL)',
    'ST': 'Demokratická republika Svatý Tomáš a Princův ostrov',
    'VC': 'Svatý Vincenc a Grenadiny',
    'SZ': 'Svazijské království',
    'SY': 'Syrská arabská republika',
    'SB': 'Šalomounovy ostrovy',
    'ES': 'Španělské království',
    'SJ': 'Špicberky a Jan Mayen',
    'LK': 'Šrílanská demokratická socialistická republika',
    'SE': 'Švédské království',
    'CH': 'Švýcarská konfederace',
    'TJ': 'Republika Tádžikistán',
    'TZ': 'Tanzanská sjednocená republika',
    'TH': 'Thajské království',
    'TW': 'Čínská republika (Tchaj-wan)',
    'TG': 'Tožská republika',
    'TK': 'Tokelau',
    'TO': 'Království Tonga',
    'TT': 'Republika Trinidad a Tobago',
    'TN': 'Tuniská republika',
    'TR': 'Turecká republika',
    'TM': 'Turkmenistán',
    'TC': 'Ostrovy Turks a Caicos',
    'TV': 'Tuvalu',
    'UG': 'Ugandská republika',
    'UA': 'Ukrajina',
    'UY': 'Uruguayská východní republika',
    'UZ': 'Republika Uzbekistán',
    'CX': 'Území Vánoční ostrov',
    'VU': 'Republika Vanuatu',
    'VA': 'Vatikánský městský stát',
    'GB': 'Spojené království Velké Británie a Severního Irska',
    'VE': 'Bolívarovská republika Venezuela',
    'VN': 'Vietnamská socialistická republika',
    'TL': 'Demokratická republika Východní Timor',
    'WF': 'Teritorium Wallisovy ostrovy a Futuna',
    'ZM': 'Zambijská republika',
    'EH': 'Saharská arabská demokratická republika',
    'ZW': 'Zimbabwská republika'
}