# Generated by Django 3.1.1 on 2020-09-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('lau1_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nuts3_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField()),
                ('age', models.PositiveSmallIntegerField(verbose_name="Person's age at death")),
                ('gender', models.CharField(max_length=1)),
                ('associated_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid_app.county')),
                ('associated_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid_app.region')),
            ],
        ),
    ]
