# Generated by Django 3.1.1 on 2020-09-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NUTS_0_AREA',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NUTS_1_AREA',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nuts_higher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.nuts_0_area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NUTS_2_AREA',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nuts_higher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.nuts_1_area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NUTS_3_AREA',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nuts_higher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.nuts_2_area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformedTests',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('test_count', models.PositiveIntegerField(verbose_name='Total number of performed tests at given day')),
            ],
        ),
        migrations.CreateModel(
            name='NUTS_4_AREA',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nuts_higher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.nuts_3_area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_death', models.DateField()),
                ('age', models.PositiveSmallIntegerField(verbose_name="Person's age at death")),
                ('gender', models.CharField(max_length=1)),
                ('nuts_4_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.nuts_4_area')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age at the time of the report')),
                ('gender', models.CharField(max_length=1)),
                ('nuts_4_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.nuts_4_area')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.nuts_0_area')),
            ],
        ),
    ]
