# Generated by Django 3.1.1 on 2020-09-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('csu_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='deceased',
            name='associated_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.county'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='associated_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.region'),
        ),
        migrations.CreateModel(
            name='ConfirmedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age at the time of the report')),
                ('gender', models.CharField(max_length=1)),
                ('associated_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.county')),
                ('associated_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_app.region')),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='covid_app.country')),
            ],
        ),
    ]
